version: '3.7'

services:
  iris:
    build:
      context: ./IRIS
      dockerfile: Dockerfile
    image: isjdctemplate:nativeapi-iris
    init: true
    hostname: nativeapi-iris
    container_name: nativeapi-iris
    ports:
      # webserver/management portal port
      - "52779:52773"
      # superserver default port
      - "1972:1972"
    environment:
      TZ: JST-9

  nodejs:
    build:
      context: ./Node.js
      dockerfile: Dockerfile
    image: isjdctemplate:nativeapi-nodejs
    init: true
    hostname: nativeapi-nodejs
    container_name: nativeapi-nodejs
    environment:
      - TZ=JST-9
    ports:
      - "8080:8080"
    volumes:
      - ./src:/ISC
